#!/bin/bash
# Copyright (C) Unipi Technology spol. s r.o. - All Rights Reserved
# SPDX-License-Identifier: MIT
#
# @author Miroslav Ondra <ondra@unipi.technology>
# @author Unipi Technology <info@unipi.technology>
# @date 2024-10-07

# This is mmdebstrap customize hook forces firmware update on first boot

set -eu

TARGET=$1

if test "${MMDEBSTRAP_MODE:-}" = chrootless; then
    systemctl --root "$TARGET" enable unipifwupdate.service || true
else
    chroot "$TARGET" systemctl enable unipifwupdate.service || true
fi
