#!/bin/bash
# Copyright (C) Unipi Technology spol. s r.o. - All Rights Reserved
# SPDX-License-Identifier: MIT
#
# @author Miroslav Ondra <ondra@unipi.technology>
# @author UniPi <info@unipi.technology>
# @date 2024-10-07

# This is mmdebstrap customize hook to create
# /etc/fstab with predefined volumes

set -eu

cat <<EOF > "$1/etc/fstab"
tmpfs /tmp tmpfs nodev,size=150m 0 0
EOF
