#!/bin/bash
# Copyright (C) Unipi Technology spol. s r.o. - All Rights Reserved
# SPDX-License-Identifier: MIT
#
# @author Miroslav Ondra <ondra@unipi.technology>
# @author Unipi Technology <info@unipi.technology>
# @date 2024-10-07

# This is mmdebstrap customize hook to add user unipi
# with sudo

set -eu

chroot "$1" adduser --disabled-password --gecos "" ${SUDO_USERNAME} || true
chroot "$1" groupadd -r i2c || true
chroot "$1" groupadd -r spi || true
chroot "$1" groupadd -r gpio || true
chroot "$1" groupadd -r dialout || true
chroot "$1" groupadd -r sudo || true
chroot "$1" usermod -a -G i2c,spi,gpio,dialout,sudo ${SUDO_USERNAME} || true

cat <<EOF > "$1/etc/sudoers.d/${SUDO_USERNAME}"
${SUDO_USERNAME} ALL=(ALL) ALL
EOF

if [ "$SUDO_PASSWD" = "y" ]; then
    if echo "$SUDO_PASSWD_TEXT" | grep -q '^|[[:digit:]]|'; then
        PW=$(echo "$SUDO_PASSWD_TEXT" | sed 's/|/$/g')
    else
        PW=$(echo "$SUDO_PASSWD_TEXT" | openssl passwd -5 -stdin)
    fi
    echo "$SUDO_USERNAME:$PW" | /sbin/chpasswd -R "$1" -e
fi
