#!/bin/bash
# Copyright (C) Unipi Technology spol. s r.o. - All Rights Reserved
# SPDX-License-Identifier: MIT
#
# @author Miroslav Ondra <ondra@unipi.technology>
# @author Unipi Technology <info@unipi.technology>
# @date 2024-10-07

# This is mmdebstrap customize hook that clear any ssh hostkeys and 
# add service regenerate_ssh_host_keys to create new one after first run

set -eu

TARGET=$1

if test "${MMDEBSTRAP_MODE:-}" = chrootless; then
    systemctl --root "$TARGET" enable sshd-keygen regenerate_ssh_host_keys.service
else
    chroot "$TARGET" systemctl enable sshd-keygen regenerate_ssh_host_keys.service
fi

rm -f "$TARGET/etc/ssh/ssh_host"*

mkdir -p $TARGET/etc/systemd/system/sshd-keygen.service.d
cat > $TARGET/etc/systemd/system/sshd-keygen.service.d/override.conf <<EOF
[Unit]
ConditionFirstBoot=
ConditionPathExists=/run/regenerate-ssh
[Service]
ExecStartPost=-/bin/systemctl disable --no-block --no-reload -q regenerate_ssh_host_keys
EOF
